### ISSUE TITLE
Thread error 

### ISSUE THREAD

**Issue by trickalia** [cooldogepm/BedrockEconomy#91] opened 2023-06-10 13:42 UTC
broken chain of object ownership that happens when the thread creating the object stopped using it before it could be dereferenced by another thread.

I have a skyblock plugin i got lisenced but i keep getting this error. it got nothing do with my plugin but is to do with the bedrockeconomy not threading correctly

**To Reproduce**
1. Click on 'join my island'
2. what should do: 'uses a bedrock economy as a dependency and loads the island and matches the config rules 
3. checks everything is in correct order of generation and what it needs to run 
5. See error

**Expected behavior**
should load my island without crashing 

[13:30:42.623] [Server thread/CRITICAL]: pmmp\thread\ConnectionException: "pmmpthread detected an attempt to connect to an object which has already been destroyed" (EXCEPTION) in "plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/libs/cooldogedev/libSQL/ConnectionPool" at line 69
--- Stack trace ---
  #0 plugins/BedrockEconomy.phar/src/cooldogedev/BedrockEconomy/libs/cooldogedev/libSQL/ConnectionPool(69): pmmp\thread\ThreadSafeArray->shift()
  #1 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): cooldogedev\BedrockEconomy\libs\cooldogedev\libSQL\ConnectionPool->cooldogedev\BedrockEconomy\libs\cooldogedev\libSQL\{closure}()
  #2 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #3 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #4 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1686403842.6697)
  #5 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #6 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #7 pmsrc/src/PocketMine(357): pocketmine\server()
  #8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---```

**Screenshots**
```![image](https://github.com/cooldogepm/BedrockEconomy/assets/39748350/61e6a06f-1c03-421d-aa51-cb835ad13055)

**OS and version (please complete the following information):**
 - Server OS: [e.g. Windows 11]
 - PocketMine-MP version [5.0.1]

**Additional context**
could be my plugin but i contacted the dev team that i licensed to make it said its bedrock economy error.

please fix

**Comment by cooldogedev** [comment] 2023-06-10 16:36
Could you try this development [version](https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:37)

**Comment by trickalia** [comment] 2023-06-10 17:11
which version

**Comment by cooldogedev** [comment] 2023-06-10 17:47
This one: https://poggit.pmmp.io/ci/cooldogepm/BedrockEconomy/BedrockEconomy/dev:37

**Comment by cooldogedev** [comment] 2023-06-11 02:34
This is a duplicate of https://github.com/cooldogepm/BedrockEconomy/issues/90, use the dev version I sent above and it should fix it.

**Closed by cooldogedev** 2023-06-11 02:34 UTC
